name: Build and Deploy Uplink

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t uplink:latest .

      - name: Tag Docker image
        run: docker tag uplink:latest localhost:5000/uplink:live

      - name: Push Docker image
        run: docker push localhost:5000/uplink:live
